version: "2"

volumes:
  craftcms-data:
  postgresql-data:
  redis-data:
  craftcms-logs:

services:
  web:
    image: wyveo/craftcms-docker:latest
    restart: unless-stopped
    ports:
      - 9005:80
    volumes:
      - craftcms-logs:/var/log
      - craftcms-data:/usr/share/nginx
    links:
      - postgres
      - redis
    # env vars are replaced in .env
    environment:
      # Set locale to UTF-8 (https://oncletom.io/2015/docker-encoding/)
      LANG: C.UTF-8

      # REDIS is linked
      REDIS_HOST: redis
      REDIS_PORT_6379_TCP: tcp://redis:6379

      # DB is linked
      DB_DRIVER: pgsql
      DB_SERVER: postgres
      DB_DATABASE: craft3
      DB_PASSWORD: lkasjdf
      PGPASSWORD: lkasjdf
      DB_SCHEMA: public
      DB_PORT: "5432"
      DB_USER: craft3

      ASSET_BASE_URL: "//localhost:9005/assets"
      ASSET_FS_PATH: "/usr/share/nginx/web/assets"

  postgres:
    image: postgres:11.5
    restart: unless-stopped
    environment:
      POSTGRES_USER: craft3
      POSTGRES_PASSWORD: lkasjdf
      POSTGRES_DB: craft3
      POSTGRES_INITDB_ARGS: "-E UTF8"
    volumes:
      # Persistent data
      - postgresql-data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.6-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
